[build]
  command = "npx turbo run build --filter=web"
  publish = "apps/web/out"
  base = ""

[build.environment]
  NODE_VERSION = "20"
  NEXT_PUBLIC_SUPABASE_URL = "https://rgkymvhoewbozvxonlft.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "sb_publishable_AdPg8ID7Obr5T_FQplnYdg_4hV5tg73"
